sonar.projectKey=prosheva-adi_eventflow-eindhoven
sonar.organization=prosheva-adi

sonar.sources=backend/src/main,frontend/src
sonar.tests=backend/src/test

sonar.java.binaries=backend/build/classes
sonar.java.test.binaries=backend/build/classes/java/test
sonar.coverage.jacoco.xmlReportPaths=backend/build/reports/jacoco/test/jacocoTestReport.xml