spring.datasource.url=jdbc:postgresql://localhost:5432/eventflow
spring.datasource.username=postgres
spring.datasource.password=Maksp2@@3
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.flywaydb=DEBUG